name: Deploy to GitHub Pages

on:
  push:
    # Trigger the workflow on push to the 'main' branch
    branches:
      - main
      - development
  workflow_dispatch:     # Allows the workflow to be manually triggered from the Actions tab

permissions:
  contents: read       # Grant permission to read repository content
  pages: write         # Grant permission to write to GitHub Pages
  id-token: write      # Grant permission for secure authentication

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3