name: Deploy

on:
  push:
    tags:
      - '1.*.*'
      - '1.*.*-RC*'

jobs:
  deploy-main:
    if: startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/tags/1.*.*'  # check tags like '1.0.0', '1.1.0'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy to Production
        run: |
          echo "Building and deploying to main..."
          # Ajouter ici tes étapes de build et de déploiement pour la branche `main`

  build-dev:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-rc')  # Tags like 1.0.2-rc1, 1.1.0-rc2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Development
        run: |
          echo "Building for development..."
          # Ajouter ici tes étapes de build pour la branche `development`
